In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression ,LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC , SVR
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import r2_score, mean_absolute_error , mean_squared_error
import os

import joblib as jb
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.pipeline import Pipeline

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
import pandas as pd
df=pd.read_csv('heart_new.csv')
df.head()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40      M           ATA        140          289          0     Normal   
1   49      F           NAP        160          180          0     Normal   
2   37      M           ATA        130          283          0         ST   
3   48      F           ASY        138          214          0     Normal   
4   54      M           NAP        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

In [6]:
df.tail()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [7]:
df.isna().sum()

Age               0
Gender            0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Gender          918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [10]:
maps = {}
def find_category_mappings(df, variable):
    return {k: i for i, k in enumerate(df[variable].unique())}

def integer_encode(df, variable, ordinal_mapping):
    df[variable] =  df[variable].map(ordinal_mapping)
    maps[variable] = mappings
    
for variable in df.columns:
    if df[variable].dtype == "object":
        mappings = find_category_mappings(df, variable)
        integer_encode(df, variable,  mappings)
        maps[variable] = mappings

In [11]:
maps

{'Gender': {'M': 0, 'F': 1},
 'ChestPainType': {'ATA': 0, 'NAP': 1, 'ASY': 2, 'TA': 3},
 'RestingECG': {'Normal': 0, 'ST': 1, 'LVH': 2},
 'ExerciseAngina': {'N': 0, 'Y': 1},
 'ST_Slope': {'Up': 0, 'Flat': 1, 'Down': 2}}

In [12]:
with open("map.txt", "w") as file:
    file.write(str(maps))

In [21]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [14]:
x.head()

Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40       0              0        140          289          0           0   
1   49       1              1        160          180          0           0   
2   37       0              0        130          283          0           1   
3   48       1              2        138          214          0           0   
4   54       0              1        150          195          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0    172               0      0.0         0  
1    156               0      1.0         1  
2     98               0      0.0         0  
3    108               1      1.5         1  
4    122               0      0.0         0

In [40]:
df.tail(20)

Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
898   35       0              0        122          192          0   
899   61       0              2        148          203          0   
900   58       0              2        114          318          0   
901   58       1              2        170          225          1   
902   58       0              0        125          220          0   
903   56       0              0        130          221          0   
904   56       0              0        120          240          0   
905   67       0              1        152          212          0   
906   55       1              0        132          342          0   
907   44       0              2        120          169          0   
908   63       0              2        140          187          0   
909   63       1              2        124          197          0   
910   41       0              0        120          157          0   
911   59       0              2        164          176          1   
912   57       1              2        140          241          0   
913   45       0              3        110          264          0   
914   68       0              2        144          193          1   
915   57       0              2        130          131          0   
916   57       1              0        130          236          0   
917   38       0              1        138          175          0   

     RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
898           0    174               0      0.0         0             0  
899           0    161               0      0.0         0             1  
900           1    140               0      4.4         2             1  
901           2    146               1      2.8         1             1  
902           0    144               0      0.4         1             0  
903           2    163               0      0.0         0             0  
904           0    169               0      0.0         2             0  
905           2    150               0      0.8         1             1  
906           0    166               0      1.2         0             0  
907           0    144               1      2.8         2             1  
908           2    144               1      4.0         0             1  
909           0    136               1      0.0         1             1  
910           0    182               0      0.0         0             0  
911           2     90               0      1.0         1             1  
912           0    123               1      0.2         1             1  
913           0    132               0      1.2         1             1  
914           0    141               0      3.4         1             1  
915           0    115               1      1.2         1             1  
916           2    174               0      0.0         1             1  
917           0    173               0      0.0         0             0

In [17]:
# x=x.values()
# x

In [18]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

###  cutting out test samples

In [14]:
# df.iloc[2:3].to_csv('heart1.csv')
# df.iloc[3:4].to_csv('heart2.csv')

In [26]:
r3 = x.iloc[3:4]
r3

Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
3   48       1              2        138          214          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
3    108               1      1.5         1

######  rows with label 1 ----> 3,500,115,900

In [27]:
l3 = y.iloc[3:4]
l3

3    1
Name: HeartDisease, dtype: int64

In [28]:
l500 = y.iloc[500:501]
l500

500    1
Name: HeartDisease, dtype: int64

In [33]:
l115 = y.iloc[115:116]
l115

115    1
Name: HeartDisease, dtype: int64

In [41]:
l900 = y.iloc[900 :901]
l900 

900    1
Name: HeartDisease, dtype: int64

######  rows with label 0 ----> 600 , 800 , 80 , 55

In [29]:
l600 = y.iloc[600:601]
l600

600    0
Name: HeartDisease, dtype: int64

In [30]:
l800 = y.iloc[800:801]
l800

800    0
Name: HeartDisease, dtype: int64

In [31]:
l80 = y.iloc[80:81]
l80

80    0
Name: HeartDisease, dtype: int64

In [32]:
l55 = y.iloc[55:56]
l55

55    0
Name: HeartDisease, dtype: int64

######  save to csv files

In [51]:
x.iloc[3:4].to_csv('test3.csv')

In [52]:
x.iloc[500:501].to_csv('test500.csv')

In [53]:
x.iloc[115:116].to_csv('test115.csv')

In [54]:
x.iloc[900:901].to_csv('test900.csv')

In [55]:
x.iloc[600:601].to_csv('test600.csv')

In [56]:
x.iloc[800:801].to_csv('test800.csv')

In [57]:
x.iloc[80:81].to_csv('test80.csv')

In [58]:
x.iloc[55:56].to_csv('test55.csv')

In [15]:
from collections import Counter

In [16]:
Counter(y)  

Counter({0: 410, 1: 508})

In [17]:
from imblearn.over_sampling import RandomOverSampler 

In [18]:
ros = RandomOverSampler(random_state=42)
X_res, y_res=ros.fit_resample(x, y)

In [19]:
Counter(y_res)

Counter({0: 508, 1: 508})

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(X_res, y_res,test_size=0.2)
x_train

array([[43. ,  0. ,  2. , ...,  1. ,  2. ,  1. ],
       [59. ,  0. ,  2. , ...,  0. ,  1. ,  1. ],
       [69. ,  0. ,  2. , ...,  0. ,  1. ,  1. ],
       ...,
       [64. ,  0. ,  2. , ...,  1. ,  1. ,  1. ],
       [62. ,  0. ,  1. , ...,  1. ,  1.2,  1. ],
       [55. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [22]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [23]:
LogisticRegression

sklearn.linear_model._logistic.LogisticRegression

In [24]:
y_pred=lr.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac=accuracy_score(y_test,y_pred)
ac

0.8260869565217391

In [38]:
cf=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)

In [39]:
cf

array([[61, 15],
       [17, 91]], dtype=int64)

In [40]:
cr

'              precision    recall  f1-score   support\n\n           0       0.78      0.80      0.79        76\n           1       0.86      0.84      0.85       108\n\n    accuracy                           0.83       184\n   macro avg       0.82      0.82      0.82       184\nweighted avg       0.83      0.83      0.83       184\n'

In [26]:
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
y_predict=dtc_clf.predict(x_test)
y_predict

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [43]:
from sklearn.metrics import accuracy_score
ac1=accuracy_score(y_test,y_predict)
ac1

0.7608695652173914

In [29]:
import joblib

In [44]:
cf1=confusion_matrix(y_test,y_predict)
cr1=classification_report(y_test,y_predict)

In [45]:
cf1

array([[61, 15],
       [29, 79]], dtype=int64)

In [46]:
cr1

'              precision    recall  f1-score   support\n\n           0       0.68      0.80      0.73        76\n           1       0.84      0.73      0.78       108\n\n    accuracy                           0.76       184\n   macro avg       0.76      0.77      0.76       184\nweighted avg       0.77      0.76      0.76       184\n'

In [ ]:
joblib.dump(lr,"lr2.joblib")+

['lr2.joblib']

In [31]:
from sklearn.ensemble import RandomForestClassifier
rmf=RandomForestClassifier(max_depth=3,random_state=0)
rmf_clf=rmf.fit(x_train,y_train)

In [32]:
y_predict1=rmf_clf.predict(x_test)
y_predict1

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
ac1=accuracy_score(y_test,y_predict1)
ac1

0.8478260869565217

In [34]:
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Flatten
from sklearn.metrics import accuracy_score
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


x_normalized = (x - x.mean()) / x.std()

time_steps = 10
num_features = x_normalized.shape[1]

num_samples = x_normalized.shape[0] - time_steps + 1
x_reshaped = np.array([x_normalized[i:i+time_steps] for i in range(num_samples)])

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
onehot_encoder = OneHotEncoder(sparse=False)
y_onehot = onehot_encoder.fit_transform(y_encoded.reshape(-1, 1))
y_reshaped = y_onehot[time_steps - 1:]

xtrain, xtest, ytrain, ytest = train_test_split(x_reshaped, y_reshaped, test_size=0.1, random_state=42)

model = Sequential([
    LSTM(128, input_shape=(time_steps, num_features), return_sequences=True, activation='relu'),
    LSTM(64, return_sequences=True, activation='relu'),
    LSTM(32, activation='relu'),
    Dense(24, activation='relu'),
    Dropout(0.5),
    Flatten(),  
    Dense(ytrain.shape[1], activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


model.fit(xtrain, ytrain, epochs=360, batch_size=32, validation_split=0.1)


loss, accuracy = model.evaluate(xtest, ytest)
print("Loss:", loss)
print("Accuracy:", accuracy)


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Train on 736 samples, validate on 82 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/360
736/736 [==============================] - 2s 3ms/sample - loss: 0.6800 - acc: 0.5435 - val_loss: 0.6184 - val_acc: 0.5976
Epoch 2/360
736/736 [==============================] - 1s 729us/sample - loss: 0.6272 - acc: 0.6168 - val_loss: 0.5742 - val_acc: 0.6341
Epoch 3/360
736/736 [==============================] - 0s 641us/sample - loss: 0.6380 - acc: 0.5897 - val_loss: 0.6043 - val_acc: 0.6585
Epoch 4/360
736/736 [==============================] - 0s 598us/sample - loss: 0.6376 - acc: 0.5992 - val_loss: 0.5690 - val_acc: 0.6585
Epoch 5/360
736/736 [==============================] - 0s 619us/sample - loss: 0.6403 - acc: 0.6168 - val_loss: 0.5880 - val_acc: 0.6463
Epoch 6/360
736/736 [================

736/736 [==============================] - 0s 618us/sample - loss: 0.4476 - acc: 0.7785 - val_loss: 0.6063 - val_acc: 0.6829
Epoch 113/360
736/736 [==============================] - 0s 619us/sample - loss: 0.5062 - acc: 0.7677 - val_loss: 0.4866 - val_acc: 0.7683
Epoch 114/360
736/736 [==============================] - 0s 599us/sample - loss: 0.4569 - acc: 0.7921 - val_loss: 0.4771 - val_acc: 0.7561
Epoch 115/360
736/736 [==============================] - 0s 630us/sample - loss: 0.4541 - acc: 0.7948 - val_loss: 0.5282 - val_acc: 0.7317
Epoch 116/360
736/736 [==============================] - 0s 597us/sample - loss: 0.4382 - acc: 0.7867 - val_loss: 0.5735 - val_acc: 0.7073
Epoch 117/360
736/736 [==============================] - 0s 609us/sample - loss: 0.4149 - acc: 0.8139 - val_loss: 0.4941 - val_acc: 0.7561
Epoch 118/360
736/736 [==============================] - 0s 598us/sample - loss: 0.4579 - acc: 0.8084 - val_loss: 0.5015 - val_acc: 0.7561
Epoch 119/360
736/736 [==================

736/736 [==============================] - 0s 654us/sample - loss: 0.2239 - acc: 0.9049 - val_loss: 0.6916 - val_acc: 0.7439
Epoch 172/360
736/736 [==============================] - 0s 661us/sample - loss: 0.1837 - acc: 0.9293 - val_loss: 0.8736 - val_acc: 0.7683
Epoch 173/360
736/736 [==============================] - 0s 673us/sample - loss: 0.1808 - acc: 0.9348 - val_loss: 1.1180 - val_acc: 0.7805
Epoch 174/360
736/736 [==============================] - 0s 661us/sample - loss: 0.1938 - acc: 0.9266 - val_loss: 1.1557 - val_acc: 0.7561
Epoch 175/360
736/736 [==============================] - 0s 650us/sample - loss: 0.1671 - acc: 0.9375 - val_loss: 1.2118 - val_acc: 0.7561
Epoch 176/360
736/736 [==============================] - 0s 640us/sample - loss: 0.1993 - acc: 0.9226 - val_loss: 1.1571 - val_acc: 0.7439
Epoch 177/360
736/736 [==============================] - 1s 683us/sample - loss: 0.1982 - acc: 0.9198 - val_loss: 1.1031 - val_acc: 0.7439
Epoch 178/360
736/736 [==================

736/736 [==============================] - 1s 748us/sample - loss: 0.0508 - acc: 0.9864 - val_loss: 2.1488 - val_acc: 0.7683
Epoch 231/360
736/736 [==============================] - 1s 703us/sample - loss: 0.0659 - acc: 0.9783 - val_loss: 2.0826 - val_acc: 0.7683
Epoch 232/360
736/736 [==============================] - 1s 704us/sample - loss: 0.0483 - acc: 0.9864 - val_loss: 2.2347 - val_acc: 0.7683
Epoch 233/360
736/736 [==============================] - 1s 728us/sample - loss: 0.0386 - acc: 0.9905 - val_loss: 2.0549 - val_acc: 0.7561
Epoch 234/360
736/736 [==============================] - 1s 703us/sample - loss: 0.1707 - acc: 0.9402 - val_loss: 2.0947 - val_acc: 0.7317
Epoch 235/360
736/736 [==============================] - 1s 693us/sample - loss: 0.1817 - acc: 0.9266 - val_loss: 1.8060 - val_acc: 0.7317
Epoch 236/360
736/736 [==============================] - 1s 682us/sample - loss: 0.0948 - acc: 0.9633 - val_loss: 1.5855 - val_acc: 0.7439
Epoch 237/360
736/736 [==================

736/736 [==============================] - 0s 662us/sample - loss: 0.0027 - acc: 0.9986 - val_loss: 3.1569 - val_acc: 0.7561
Epoch 290/360
736/736 [==============================] - 0s 661us/sample - loss: 0.0025 - acc: 0.9986 - val_loss: 3.1414 - val_acc: 0.7683
Epoch 291/360
736/736 [==============================] - 0s 662us/sample - loss: 0.0051 - acc: 0.9959 - val_loss: 3.1153 - val_acc: 0.7683
Epoch 292/360
736/736 [==============================] - 0s 661us/sample - loss: 0.0024 - acc: 1.0000 - val_loss: 3.0987 - val_acc: 0.7683
Epoch 293/360
736/736 [==============================] - 0s 661us/sample - loss: 0.0020 - acc: 1.0000 - val_loss: 2.9787 - val_acc: 0.7805
Epoch 294/360
736/736 [==============================] - 0s 663us/sample - loss: 0.0041 - acc: 0.9986 - val_loss: 2.9575 - val_acc: 0.7805
Epoch 295/360
736/736 [==============================] - 0s 661us/sample - loss: 9.1121e-04 - acc: 1.0000 - val_loss: 2.8617 - val_acc: 0.7927
Epoch 296/360
736/736 [==============

736/736 [==============================] - 1s 685us/sample - loss: 0.0016 - acc: 1.0000 - val_loss: 3.1798 - val_acc: 0.7561
Epoch 349/360
736/736 [==============================] - 1s 832us/sample - loss: 0.2545 - acc: 0.9688 - val_loss: 3.0108 - val_acc: 0.6707
Epoch 350/360
736/736 [==============================] - 1s 834us/sample - loss: 0.4075 - acc: 0.8641 - val_loss: 1.0023 - val_acc: 0.7073
Epoch 351/360
736/736 [==============================] - 1s 728us/sample - loss: 0.2792 - acc: 0.8736 - val_loss: 1.2963 - val_acc: 0.7073
Epoch 352/360
736/736 [==============================] - 1s 876us/sample - loss: 0.1556 - acc: 0.9375 - val_loss: 1.3054 - val_acc: 0.7195
Epoch 353/360
736/736 [==============================] - 1s 725us/sample - loss: 0.0892 - acc: 0.9755 - val_loss: 1.9879 - val_acc: 0.7073
Epoch 354/360
736/736 [==============================] - 1s 950us/sample - loss: 0.0551 - acc: 0.9837 - val_loss: 1.9006 - val_acc: 0.7073
Epoch 355/360
736/736 [==================